AWSTemplateFormatVersion: 2010-09-09
Resources:
  NextBucket:
    Type: 'AWS::S3::Bucket'
    Properties: {}
  NextCloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          TargetOriginId: MyCDN
          ViewerProtocolPolicy: 'https-only'
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        Enabled: true
        Origins:
          - Id: MyCDN
            DomainName: !GetAtt NextBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${NextCloudFrontOAI}
    DependsOn: NextBucket
  NextCloudFrontOAI:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "mycdn-access-identity"
